### ISSUE TITLE
Problem with imports using pyinstaller

### ISSUE THREAD

**Issue by parksj10** [webcomics/pywine#12]
I've tested a local build of my software

<details>
<summary>Local Windows 10 Pyinstaller (amd64) output</summary>
<p>

```
(ve-pas) C:\Users\Josh\Code\photonics_release\Analysis>pyinstaller ..\..\pas\src\pas\cusum_hmm\state_analysis.py
318 INFO: PyInstaller: 4.8
319 INFO: Python: 3.9.6 (conda)
337 INFO: Platform: Windows-10-10.0.19043-SP0
338 INFO: wrote C:\Users\Josh\Code\photonics_release\Analysis\state_analysis.spec
394 INFO: UPX is available.
398 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Josh\\Code\\pas\\src']
773 INFO: checking Analysis
774 INFO: Building Analysis because Analysis-00.toc is non existent
774 INFO: Initializing module dependency graph...
778 INFO: Caching module graph hooks...
800 INFO: Analyzing base_library.zip ...
4050 INFO: Processing pre-find module path hook distutils from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
4053 INFO: distutils: retargeting to non-venv dir 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib'
7969 INFO: Caching module dependency graph...
8251 INFO: running Analysis Analysis-00.toc
8257 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\tools\miniconda3\envs\ve-pas\python.exe
8600 INFO: Analyzing C:\Users\Josh\Code\pas\src\pas\cusum_hmm\state_analysis.py
9545 INFO: Processing pre-find module path hook site from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
9547 INFO: site: retargeting to fake-dir 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\fake-modules'
16521 INFO: Processing pre-safe import module hook six.moves from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
25223 INFO: Processing pre-safe import module hook win32com from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
27165 INFO: Processing module hooks...
27166 INFO: Loading module hook 'hook-llvmlite.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
27189 INFO: Loading module hook 'hook-numba.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
27230 INFO: Loading module hook 'hook-difflib.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27238 INFO: Loading module hook 'hook-distutils.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27240 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27248 INFO: Loading module hook 'hook-encodings.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27409 INFO: Loading module hook 'hook-heapq.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27415 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27478 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27486 INFO: Loading module hook 'hook-numpy.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27564 WARNING: Conda distribution 'numpy', dependency of 'numpy', was not found. If you installed this distribution with pip then you may ignore this warning.
27609 INFO: Import to be excluded not found: 'f2py'
27640 INFO: Loading module hook 'hook-numpy._pytesttester.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
27648 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
28471 INFO: Loading module hook 'hook-pandas.plotting.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
28556 INFO: Loading module hook 'hook-pandas.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
29657 INFO: Loading module hook 'hook-pickle.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
29663 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
30347 WARNING: Hidden import "pkg_resources.py2_warn" not found!
30347 WARNING: Hidden import "pkg_resources.markers" not found!
30362 INFO: Loading module hook 'hook-pytz.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
30672 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
31779 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
31942 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
31944 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
32195 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
32198 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
32201 INFO: Loading module hook 'hook-xml.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
32204 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
32445 INFO: checking Tree
32446 INFO: Building Tree because Tree-00.toc is non existent
32449 INFO: Building Tree Tree-00.toc
32593 INFO: checking Tree
32594 INFO: Building Tree because Tree-01.toc is non existent
32597 INFO: Building Tree Tree-01.toc
32754 INFO: checking Tree
32754 INFO: Building Tree because Tree-02.toc is non existent
32757 INFO: Building Tree Tree-02.toc
32766 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks'...
32861 INFO: Looking for ctypes DLLs
33147 INFO: Analyzing run-time hooks ...
33178 INFO: Including run-time hook 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
33185 INFO: Including run-time hook 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
33191 INFO: Including run-time hook 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
33196 INFO: Including run-time hook 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
33204 INFO: Including run-time hook 'C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
33241 INFO: Looking for dynamic libraries
34001 INFO: Looking for eggs
34002 INFO: Using Python library C:\tools\miniconda3\envs\ve-pas\python39.dll
34007 INFO: Found binding redirects:
[]
34029 INFO: Warnings written to C:\Users\Josh\Code\photonics_release\Analysis\build\state_analysis\warn-state_analysis.txt
34352 INFO: Graph cross-reference written to C:\Users\Josh\Code\photonics_release\Analysis\build\state_analysis\xref-state_analysis.html
34441 INFO: checking PYZ
34441 INFO: Building PYZ because PYZ-00.toc is non existent
34445 INFO: Building PYZ (ZlibArchive) C:\Users\Josh\Code\photonics_release\Analysis\build\state_analysis\PYZ-00.pyz
36829 INFO: Building PYZ (ZlibArchive) C:\Users\Josh\Code\photonics_release\Analysis\build\state_analysis\PYZ-00.pyz completed successfully.
36907 INFO: checking PKG
36907 INFO: Building PKG because PKG-00.toc is non existent
36911 INFO: Building PKG (CArchive) state_analysis.pkg
36983 INFO: Building PKG (CArchive) state_analysis.pkg completed successfully.
36987 INFO: Bootloader C:\tools\miniconda3\envs\ve-pas\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
36987 INFO: checking EXE
36988 INFO: Building EXE because EXE-00.toc is non existent
36989 INFO: Building EXE from EXE-00.toc
36991 INFO: Copying bootloader EXE to C:\Users\Josh\Code\photonics_release\Analysis\build\state_analysis\state_analysis.exe
37001 INFO: Copying icon to EXE
37001 INFO: Copying icons from ['C:\\tools\\miniconda3\\envs\\ve-pas\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
37104 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
37104 INFO: Writing RT_ICON 1 resource with 3752 bytes
37110 INFO: Writing RT_ICON 2 resource with 2216 bytes
37111 INFO: Writing RT_ICON 3 resource with 1384 bytes
37113 INFO: Writing RT_ICON 4 resource with 37019 bytes
37114 INFO: Writing RT_ICON 5 resource with 9640 bytes
37115 INFO: Writing RT_ICON 6 resource with 4264 bytes
37116 INFO: Writing RT_ICON 7 resource with 1128 bytes
37126 INFO: Copying 0 resources to EXE
37127 INFO: Emedding manifest in EXE
37130 INFO: Updating manifest in C:\Users\Josh\Code\photonics_release\Analysis\build\state_analysis\state_analysis.exe
37216 INFO: Updating resource type 24 name 1 language 0
37223 INFO: Appending PKG archive to EXE
41780 INFO: Building EXE from EXE-00.toc completed successfully.
41786 INFO: checking COLLECT
41786 INFO: Building COLLECT because COLLECT-00.toc is non existent
41788 INFO: Building COLLECT COLLECT-00.toc
44438 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

</p>
</details>  

<details>
<summary>Github Action pywine output</summary>
<p>

```
328 INFO: PyInstaller: 4.5.1
329 INFO: Python: 3.9.6
382 INFO: Platform: Windows-7-6.1.7601-SP1
384 INFO: wrote Z:\main_dir\state_analysis.spec
470 INFO: UPX is available.
475 INFO: Extending PYTHONPATH with paths
['Z:\\main_dir\\src', 'Z:\\main_dir']
1353 INFO: checking Analysis
1354 INFO: Building Analysis because Analysis-00.toc is non existent
1354 INFO: Initializing module dependency graph...
1364 INFO: Caching module graph hooks...
1412 INFO: Analyzing base_library.zip ...
4509 INFO: Processing pre-find module path hook distutils from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
4512 INFO: distutils: retargeting to non-venv dir 'c:\\Python39\\lib'
8281 INFO: Caching module dependency graph...
8649 INFO: running Analysis Analysis-00.toc
8662 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\Python39\python.exe
8981 INFO: Analyzing Z:\main_dir\src\pas\cusum_hmm\state_analysis.py
10185 INFO: Processing pre-find module path hook site from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
10187 INFO: site: retargeting to fake-dir 'c:\\Python39\\lib\\site-packages\\PyInstaller\\fake-modules'
18356 INFO: Processing pre-safe import module hook six.moves from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
28507 INFO: Processing pre-safe import module hook win32com from 'c:\\Python39\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
30481 INFO: Processing module hooks...
30481 INFO: Loading module hook 'hook-llvmlite.py' from 'c:\\Python39\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
30507 INFO: Loading module hook 'hook-numba.py' from 'c:\\Python39\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
30528 INFO: Loading module hook 'hook-difflib.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
30533 INFO: Loading module hook 'hook-distutils.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
30536 INFO: Loading module hook 'hook-distutils.util.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
30541 INFO: Loading module hook 'hook-encodings.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
30927 INFO: Loading module hook 'hook-heapq.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
30936 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
31311 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
31317 INFO: Loading module hook 'hook-numpy.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
31557 INFO: Import to be excluded not found: 'f2py'
31566 INFO: Loading module hook 'hook-numpy._pytesttester.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
31572 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
33255 INFO: Loading module hook 'hook-pandas.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
35621 INFO: Loading module hook 'hook-pickle.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
35630 INFO: Loading module hook 'hook-pkg_resources.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
36936 WARNING: Hidden import "pkg_resources.py2_warn" not found!
36937 WARNING: Hidden import "pkg_resources.markers" not found!
36941 INFO: Loading module hook 'hook-pytz.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
39037 INFO: Loading module hook 'hook-setuptools.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
40840 INFO: Loading module hook 'hook-sqlite3.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
41271 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
41274 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
41942 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
41945 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
41948 INFO: Loading module hook 'hook-xml.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
41950 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
42648 INFO: checking Tree
42649 INFO: Building Tree because Tree-00.toc is non existent
42649 INFO: Building Tree Tree-00.toc
43140 INFO: checking Tree
43140 INFO: Building Tree because Tree-01.toc is non existent
43140 INFO: Building Tree Tree-01.toc
43513 INFO: checking Tree
43514 INFO: Building Tree because Tree-02.toc is non existent
43514 INFO: Building Tree Tree-02.toc
43526 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks'...
43577 INFO: Looking for ctypes DLLs
43793 INFO: Analyzing run-time hooks ...
43803 INFO: Including run-time hook 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
43812 INFO: Including run-time hook 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
43817 INFO: Including run-time hook 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
43820 INFO: Including run-time hook 'c:\\Python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
43844 INFO: Looking for dynamic libraries
45126 INFO: Looking for eggs
45126 INFO: Using Python library c:\Python39\python39.dll
45126 INFO: Found binding redirects: 
[]
52980 INFO: Warnings written to Z:\main_dir\build\state_analysis\warn-state_analysis.txt
53163 INFO: Graph cross-reference written to Z:\main_dir\build\state_analysis\xref-state_analysis.html
53227 INFO: checking PYZ
53227 INFO: Building PYZ because PYZ-00.toc is non existent
53227 INFO: Building PYZ (ZlibArchive) Z:\main_dir\build\state_analysis\PYZ-00.pyz
53229 INFO: Building PYZ (ZlibArchive) Z:\main_dir\build\state_analysis\PYZ-00.pyz completed successfully.
53236 INFO: checking PKG
53236 INFO: Building PKG because PKG-00.toc is non existent
53236 INFO: Building PKG (CArchive) PKG-00.pkg
53287 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
53289 INFO: Bootloader c:\Python39\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run_d.exe
53289 INFO: checking EXE
53290 INFO: Building EXE because EXE-00.toc is non existent
53290 INFO: Building EXE from EXE-00.toc
53293 INFO: Copying icons from ['c:\\Python39\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
53295 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
53295 INFO: Writing RT_ICON 1 resource with 3752 bytes
53295 INFO: Writing RT_ICON 2 resource with 2216 bytes
53296 INFO: Writing RT_ICON 3 resource with 1384 bytes
53296 INFO: Writing RT_ICON 4 resource with 37019 bytes
53296 INFO: Writing RT_ICON 5 resource with 9640 bytes
53296 INFO: Writing RT_ICON 6 resource with 4264 bytes
53296 INFO: Writing RT_ICON 7 resource with 1128 bytes
53300 INFO: Appending archive to EXE Z:\main_dir\build\state_analysis\state_analysis.exe
53370 INFO: Building EXE from EXE-00.toc completed successfully.
53376 INFO: checking COLLECT
53377 INFO: Building COLLECT because COLLECT-00.toc is non existent
53378 INFO: Building COLLECT COLLECT-00.toc
67779 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

</p>
</details> 

While the locally compiled pyinstaller runs just fine, I get a long error trace (debug output on) from the GHA compiled one...

<details>
<summary>GHA compiled exe trace</summary>
<p>

```
import 'pandas._libs.window' # <_frozen_importlib_external.SourcelessFileLoader object at 0x000001B4D3BE5E80>
# pandas._libs.window.aggregations not found in PYZ
Traceback (most recent call last):
  File "pas\cusum_hmm\state_analysis.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "Z:\main_dir\src\pas\cusum_hmm\hmm\hmm_module.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Python39\lib\site-packages\pandas\__init__.py", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Python39\lib\site-packages\pandas\core\api.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Python39\lib\site-packages\pandas\core\groupby\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Python39\lib\site-packages\pandas\core\groupby\generic.py", line 73, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Python39\lib\site-packages\pandas\core\frame.py", line 129, in <module>
  File "<frozen importlib._bootstrap>", line 1058, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Python39\lib\site-packages\pandas\core\generic.py", line 144, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Python39\lib\site-packages\pandas\core\window\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Python39\lib\site-packages\pandas\core\window\ewm.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing aggregations: A dynamic link library (DLL) initialization routine failed.
[7512] Failed to execute script 'state_analysis' due to unhandled exception!
```

</p>
</details>  

My guess is this is caused by the Windows 7 platform on the GHA compile, but it seems that pywine attempts to set the system to Windows 10:

`wine reg add 'HKLM\Software\Microsoft\Windows NT\CurrentVersion' /v CurrentVersion /d 10.0 /f`

Any idea if this is the problem, or what this error might be caused by? Only other thought is the pyinstaller ver needs bumping in GHA

**Comment by TobiX** [comment]
Could be something with wine DLLs? There seems to be a fix for that in PyInstaller 4.10: https://github.com/pyinstaller/pyinstaller/pull/6149
