### ISSUE TITLE
Add Microsoft Visual C++ Redistributable for Visual Studio 2017

### ISSUE THREAD

**Issue by arossert** [webcomics/pywine#8]
Thanks for creating this repo, this saves me a lot of time with my PyInstaller application build.
A small suggestion adopted from [docker-pyinstaller](https://github.com/cdrx/docker-pyinstaller) to add some needed DLLs for some applications to work on all systems:

```
# install Microsoft Visual C++ Redistributable for Visual Studio 2017 dll files
RUN set -x \
    && rm -f "$W_TMP"/* \
    && wget -P "$W_TMP" https://download.visualstudio.microsoft.com/download/pr/11100230/15ccb3f02745c7b206ad10373cbca89b/VC_redist.x64.exe \
    && cabextract -q --directory="$W_TMP" "$W_TMP"/VC_redist.x64.exe \
    && cabextract -q --directory="$W_TMP" "$W_TMP/a10" \
    && cabextract -q --directory="$W_TMP" "$W_TMP/a11" \
    && cd "$W_TMP" \
    && rename 's/_/\-/g' *.dll \
    && cp "$W_TMP"/*.dll "$W_SYSTEM64_DLLS"/
```

I'm willing to create a PR if this is something you will consider adding.

**Comment by TobiX** [comment]
IIRC, they are not needed, if something else already installed them (maybe they aren't needed at all, too long ago since I messed with that stuff...), but MS ucrt is complicated, see for example https://pyinstaller.readthedocs.io/en/stable/usage.html#windows ...

When running PyInstaller from wine, I help myself like this:
https://github.com/webcomics/dosage/blob/3ed4b701ca7adb074385b734e7b5f3334bd0425c/scripts/dosage.spec#L35
This excludes the wine-ucrt-stubs and the resulting binary seems to work fine on Windows 7 to Windows 10 in my tests (and I don't have to worry if I'm allowed to redistribute those DLLs or not).

**Comment by marcelomanzo** [comment]
Unfortunately I think this is required... psutil fails to pip install for example:

Building wheel for psutil (setup.py): started
  Building wheel for psutil (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [108 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-[310](https://gitlab.com/simracingstudio/srsapp/-/jobs/3010208828#L310)
  creating build\lib.win-amd64-cpython-310\psutil
  copying psutil\_common.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_compat.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psaix.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psosx.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psposix.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\__init__.py -> build\lib.win-amd64-cpython-310\psutil
  creating build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_memory_leaks.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-310\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  Traceback (most recent call last):
    File "C:\Python310\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
      dist.run_commands()
    File "C:\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "C:\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Python310\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
      self.distribution.run_command(command)
    File "C:\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Python310\lib\site-packages\setuptools\command\build.py", line 24, in run
      super().run()
    File "C:\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
      self.distribution.run_command(command)
    File "C:\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Python310\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 459, in build_extensions
      self._build_extensions_serial()
    File "C:\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 485, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Python310\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Python310\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 540, in build_extension
      objects = self.compiler.compile(
    File "C:\Python310\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 361, in compile
      self.initialize()
    File "C:\Python310\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 241, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Python310\lib\site-packages\setuptools\msvc.py", line [316](https://gitlab.com/simracingstudio/srsapp/-/jobs/3010208828#L316), in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Python310\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\users\root\Temp\pip-install-og3sh7jb\psutil_d2ce88b9b8d14dc2a3e32a2b4660d1b8\setup.py", line [393](https://gitlab.com/simracingstudio/srsapp/-/jobs/3010208828#L393), in main
      setup(**kwargs)
    File "C:\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Python310\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
      return run_commands(dist)
    File "C:\Python310\lib\site-packages\setuptools\_distutils\core.py", line 207, in run_commands
      raise SystemExit("error: " + str(msg))
  SystemExit: error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\users\root\Temp\pip-install-og3sh7jb\psutil_d2ce88b9b8d14dc2a3e32a2b4660d1b8\setup.py", line 426, in <module>
      main()
    File "C:\users\root\Temp\pip-install-og3sh7jb\psutil_d2ce88b9b8d14dc2a3e32a2b4660d1b8\setup.py", line 422, in main
      print(hilite(s, ok=False), file=sys.stderr)
  TypeError: hilite() got an unexpected keyword argument 'ok'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil

**Comment by TobiX** [comment]
@marcelomanzo That's a completely different issue. This  issue was about the Visual Studio RUNTIME (the ucrt), your usecase seems to somehow wants to compile psutil, so you would need the Visual Studio COMPILER. I'm not sure how you got into this situation, since psutil provides binary wheels for Windows (and when I try `wine pip install psutil` it just installs those)

Whatever your problem, it probably has nothing to do with my docker image, so I would suggest to ask (with more details) in a bigger community like StackOverflow.
